owners:
  - 24Killusion
  - ɢʟxᴄᴋ
  
 status: online
  avatar: "renegade raider",
  status: follow @12.00am_ & @xtramari on tt
commands:
  prefix:
    - "!"
    - /
  case_insensitive: true
  only_owners: true

friends:
  invite_on_added: false
  accept_all_requests: true
  decline_all_requests: false
  invite_on_startup: true
  add_on_removed: true

party:
  dont_leave_if_owner_in_party: true
  join_on_invite: true
  join_if_party_is_empty: true
  
  add_all_members_on_join: false

turn_on: true
